num_runs: 20
num_epochs: 15000
learning_rate: 0.0001
loss_name: EEGM
regularizer: regularizer_3
sigma: 0.008
weight_decay: 0.0001
dataset_name: connectionist_bench
dataset_path: ./data/connectionist_bench
split_ratio: 0.7
num_features: 60
experiment_name: connectionist_bench_eegml0_reg3