num_runs: 20
num_epochs: 15000
learning_rate: 0.0001
loss_name: EEGM
regularizer: regularizer_2
sigma: 0.008
weight_decay: 0.0001
dataset_name: ionosphere
dataset_path: ./data/ionosphere
split_ratio: 0.7
num_features: 34
experiment_name: ionosphere_eegml0_reg2