num_runs: 20
num_epochs: 15000
learning_rate: 0.0001
loss_name: EEGM
regularizer: regularizer_1
sigma: 0.008
weight_decay: 0.0001
dataset_name: gun_point
dataset_path: ./data/gun_point
split_ratio: 0.7
num_features: 150
experiment_name: gun_point_eegml0_reg1