num_runs: 20
num_epochs: 15000
learning_rate: 0.0001
loss_name: EEGM
regularizer: regularizer_4
sigma: 0.008
weight_decay: 0.0001
dataset_name: pima
dataset_path: ./data/pima
split_ratio: 0.7
num_features: 8
experiment_name: pima_eegml0_reg4